# Generated by Django 4.2 on 2024-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the company name",
                        max_length=100,
                        verbose_name="Company name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Enter the company address",
                        max_length=255,
                        verbose_name="Address",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        help_text="Enter the company contact info",
                        max_length=255,
                        verbose_name="Contact info",
                    ),
                ),
                (
                    "unique_code",
                    models.CharField(
                        blank=True,
                        help_text="Enter a unique code for the company",
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="Unique code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
